import RootLayout from "@/components/Layouts/RootLayout";
import Banner from "@/components/Ui/Banner/Banner";
import NewArrivals from "@/components/Ui/NewArrivals/NewArrivals";
import ProductCategory from "@/components/Ui/ProductCategory/ProductCategory";
import Head from "next/head";
import React from "react";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Win-Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Banner />
        <ProductCategory />
        <NewArrivals />
      </div>
    </>
  );
};

export default HomePage;

HomePage.getLayout = function getLayout(page) {
  return <RootLayout>{page}</RootLayout>;
};
